# Generated by Django 4.2.26 on 2025-11-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Age', models.IntegerField(blank=True, max_length=3, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=25, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hands2HopeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, max_length=5, null=True)),
                ('Feedback', models.CharField(max_length=300)),
                ('Date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hands2HopeApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('Reply', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hands2HopeApp.usertable')),
            ],
        ),
    ]
