# Generated by Django 4.2.26 on 2025-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
