# Generated by Django 4.2.26 on 2025-11-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0002_alter_feedbacktable_rating_alter_usertable_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='usertype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
