# Generated by Django 4.2.26 on 2025-11-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0003_logintable_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
