# Generated by Django 4.2.26 on 2025-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0004_alter_usertable_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintstable',
            name='Description',
        ),
        migrations.AddField(
            model_name='complaintstable',
            name='Complaints',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
