# Generated by Django 4.2.26 on 2025-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0005_remove_complaintstable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='Reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
