# Generated by Django 4.2.27 on 2026-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hands2HopeApp', '0006_alter_complaintstable_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SignName', models.CharField(blank=True, max_length=5, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
